### ISSUE TITLE
Swift Conversion 

### ISSUE THREAD

**Issue by basictheprogram** [darrellroot/SwiftNetrek#5]
I open the project and I receive a warning.

Swift Conversion
    Conversion to Swift 5 is available

<img width="244" alt="Netrek_xcodeproj" src="https://user-images.githubusercontent.com/6723257/55586388-719f9600-56ee-11e9-8471-0df7d93bdea3.png">

Probably related? If not, I'll open a new issue.

Validate Project Settings
    Update to recommended settings

<img width="248" alt="Netrek_xcodeproj" src="https://user-images.githubusercontent.com/6723257/55586435-87ad5680-56ee-11e9-9e15-b312009b7cef.png">

**Comment by darrellroot** [comment]
Those look related. Apple released a new version of Xcode and swift 5 just before I was due to release. So I released with Swift 4.2 and delayed upgrading Xcode.  The packet generation code is vulnerable to Swift version changes.  I’ll see if I have time Friday to update.

**Comment by darrellroot** [comment]
Upgraded from Swift 4.2 to Swift 5.  Fixed erroneous localization problem to fix recommended settings.  During Swift upgrade found "range" bugs in my packet analyzer code which didn't get exposed by Swift 4.2 but were exposed in Swift 5.
