### ISSUE TITLE
No profiles for 'net.networkmom.netrek' were found

### ISSUE THREAD

**Issue by basictheprogram** [darrellroot/SwiftNetrek#6]
No profiles for 'net.networkmom.netrek' were found: Xcode couldn't find any Mac App Development provisioning profiles matching 'net.networkmom.netrek'. (in target 'Netrek')

**Comment by darrellroot** [comment]
I suspect this means you are unable to build the “Netrek” target. Please confirm.  This may require setting up a second target and disabling the in-app-purchase (tip jar) code for that target. At least I’ll learn something new doing that.

**Comment by darrellroot** [comment]
In XCode there are now two targets: Netrek and Netrek-public-domain.

You should build the Netrek-public-domain target. That app does not use in-app-purchases and allows building the application without code signing.

Any files you add to the project should be added to both targets: Netrek and Netrek-public-domain. The only exception is edits to the TipController. We have 2 versions: TipController for Netrek, and TipController-public-domain for Netrek-public-domain.

I'd appreciate if you can confirm that you can successfully build against Netrek-public-domain.
