### ISSUE TITLE
HEADER_SEARCH_PATHS issue

### ISSUE THREAD

**Issue by basictheprogram** [darrellroot/SwiftNetrek#8]
The current HEADER_SEARCH_PATHS is below

```
HEADER_SEARCH_PATHS = /Users/droot/Dropbox/Netrek/Netrek/OpenSSL/include/;
```

Can this be switched to a relative path?

Really don't know Xcode, learning, I'll attempt to submit a PR.

**Comment by darrellroot** [comment]
I think this is resolved by switching to $(PROJECT_DIR)/Netrek/OpenSSL/include (and similar for lib).
